name: Deploy Meme Cooking Testnet
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "yarn install"

      - name: Lint
        run: "yarn lint"

      - name: Copy Charting Library files
        run: "./copy_charting_library_files.sh"

      - name: Svelte Check
        run: "yarn run check"

      - name: Add app name to .env
        run: echo "VITE_APP_NAME=Meme.Cooking" >> .env.testnet

      - name: Add contract connect ID to .env
        run: echo "VITE_APP_LOGO=https://raw.githubusercontent.com/Shitzu-Apes/brand-kit/main/logo/meme-cooking.webp" >> .env.testnet

      - name: Add commit hash to .env
        run: echo "VITE_COMMIT_HASH=\"${{ github.sha }}\"" >> .env.testnet

      - name: Add contract connect ID to .env
        run: echo "VITE_CONNECT_ID=factory.v10.meme-cooking.testnet" >> .env.testnet

      - name: Add Pinate JWT to .env
        run: echo "PINATA_JWT=$PINATA_JWT" >> .env.testnet
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Add Endpoint secret to .env
        run: echo "ENDPOINT_SECRET=$ENDPOINT_SECRET" >> .env.testnet
        env:
          ENDPOINT_SECRET: ${{ secrets.ENDPOINT_SECRET_TESTNET }}

      - name: Add account ID to .env
        run: echo "ACCOUNT_ID=$ACCOUNT_ID" >> .env.testnet
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID_TESTNET }}

      - name: Add private key to .env
        run: echo "PRIVATE_KEY=$PRIVATE_KEY" >> .env.testnet
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_TESTNET }}

      - name: Add WalletConnect project ID to .env
        run: echo "VITE_WC_PROJECT_ID=44dd0ed9ce175eeb72a67532fbfb6f96" >> .env.testnet

      - name: Build step
        run: "yarn vite build --mode testnet"

      - name: Upload to Cloudflare Pages
        run: yarn wrangler pages deploy --project-name meme-cooking-testnet .svelte-kit/cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
