name: Deploy Shitzu App
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "yarn install"

      - name: Lint
        run: "yarn lint"

      - name: Copy Charting Library files
        run: "./copy_charting_library_files.sh"

      # - name: Svelte Check
      #   run: "yarn run check"

      - name: Add commit hash to .env
        run: echo "VITE_COMMIT_HASH=\"${{ github.sha }}\"" >> .env

      - name: Add contract connect ID to .env
        run: echo "VITE_CONNECT_ID=shit.0xshitzu.near" >> .env

      - name: Add contract connect ID to .env
        run: echo "VITE_PLAUSIBLE_DOMAIN=app.shitzuapes.xyz" >> .env

      - name: Add WalletConnect project ID to .env
        run: echo "VITE_WC_PROJECT_ID=dba65fff73650d32ae5157f3492c379e" >> .env

      - name: Add Solana RPC URL to .env
        run: echo "VITE_SOLANA_RPC_URL=$VITE_SOLANA_RPC_URL" >> .env
        env:
          VITE_SOLANA_RPC_URL: ${{ secrets.VITE_SOLANA_RPC_URL }}

      - name: Build step
        run: "yarn build"

      - name: Upload to Cloudflare Pages
        run: yarn wrangler pages deploy --project-name shitzu-app .svelte-kit/cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
