name: Deploy Meme Cooking Testnet
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "yarn install"

      - name: Lint
        run: "yarn lint"

      - name: Copy Charting Library files
        run: "./copy_charting_library_files.sh"

      - name: Add app name to .env
        run: echo "VITE_APP_NAME=Meme.Cooking" >> .env

      - name: Add contract connect ID to .env
        run: echo "VITE_APP_LOGO=https://raw.githubusercontent.com/Shitzu-Apes/brand-kit/main/logo/meme-cooking.webp" >> .env

      - name: Add commit hash to .env
        run: echo "VITE_COMMIT_HASH=\"${{ github.sha }}\"" >> .env

      - name: Add contract connect ID to .env
        run: echo "VITE_CONNECT_ID=factory.v10.meme-cooking.testnet" >> .env

      - name: Add Pinate JWT to .env
        run: echo "VITE_PINATA_JWT=$VITE_PINATA_JWT" >> .env
        env:
          VITE_PINATA_JWT: ${{ secrets.VITE_PINATA_JWT }}

      - name: Add WalletConnect project ID to .env
        run: echo "VITE_WC_PROJECT_ID=44dd0ed9ce175eeb72a67532fbfb6f96" >> .env

      - name: Build step
        run: "yarn vite build --mode testnet"

      - name: Upload to Cloudflare Pages
        run: yarn wrangler pages deploy .svelte-kit/cloudflare
